LBVS/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from home.views import Custom404View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Custom404View.as_view()

home/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import RegexValidator, EmailValidator


class EmailErrorLog(models.Model):
    subject = models.CharField(max_length=255)
    to_email = models.EmailField()
    error_message = models.TextField()  # Store the error message
    timestamp = models.DateTimeField(auto_now_add=True)  # Automatically set the current timestamp

    class Meta:
        verbose_name_plural = "Email Error Logs"


class Employee(models.Model):
    # Field for timestamp of record creation
    timestamp = models.DateTimeField(auto_now_add=True)

    # Father's name
    fathers_name = models.CharField(max_length=100, blank=True)

    # PAN Document Upload
    upload_pan = models.FileField(upload_to='documents/pan/', blank=True, null=True)

    # Aadhar Document Upload
    upload_aadhar = models.FileField(upload_to='documents/aadhar/', blank=True, null=True)

    # Cancelled Cheque, Passbook, or Statement Upload
    cancelled_cheque_passbook_statement = models.FileField(upload_to='documents/bank_documents/', blank=True, null=True)

    # Bank details
    bank_name = models.CharField(max_length=100)
    bank_branch = models.CharField(max_length=100)
    bank_account_number = models.CharField(max_length=20, validators=[
        RegexValidator(regex=r'^\d{9,18}$', message='Enter a valid bank account number')
    ])
    bank_ifsc_code = models.CharField(max_length=11, validators=[
        RegexValidator(regex=r'^[A-Z]{4}0[A-Z0-9]{6}$', message='Enter a valid IFSC code')
    ])

    # Employment details
    date_of_joining = models.DateField()
    position = models.CharField(max_length=100)
    end_date = models.DateField(blank=True, null=True)

    # Employment status
    STATUS_CHOICES = [
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
        ('Terminated', 'Terminated'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)

    def __str__(self):
        return f"{self.fathers_name}'s Employment Record"


class Company(models.Model):
    name = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    email = models.EmailField(validators=[EmailValidator(message="Enter a valid email address.")])
    phone_number = models.CharField(max_length=15, validators=[RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")])
    address = models.TextField()
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    industry = models.CharField(max_length=100)
    website = models.URLField()
    notes = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    pan_number = models.CharField(max_length=10, unique=True, validators=[RegexValidator(regex=r'^[A-Z]{5}[0-9]{4}[A-Z]{1}$', message="Enter a valid PAN number.")])
    tan_number = models.CharField(max_length=10, unique=True, validators=[RegexValidator(regex=r'^[A-Z]{4}[0-9]{5}[A-Z]{1}$', message="Enter a valid TAN number.")])
    registration_date = models.DateField()
    type_of_business = models.CharField(max_length=100)
    nature_of_business = models.CharField(max_length=255)
    authorized_capital = models.DecimalField(max_digits=15, decimal_places=2)
    paid_up_capital = models.DecimalField(max_digits=15, decimal_places=2)
    financial_year_start = models.DateField()
    financial_year_end = models.DateField()
    audit_frequency = models.CharField(max_length=60)
    Assignees = models.ManyToManyField(User, related_name='company_Assignees')

    def __str__(self):
        return self.company_name

    class Meta:
        verbose_name_plural = "Company"


class ContactPerson(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='contact_persons')
    contact_person = models.CharField(max_length=255)
    contact_person_designation = models.CharField(max_length=100)
    contact_person_email = models.EmailField(validators=[EmailValidator(message='Enter a valid email address.')])
    contact_person_phone = models.CharField(max_length=15, validators=[RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")])

    def __str__(self):
        return f"{self.contact_person} ({self.company.company_name})"

    class Meta:
        verbose_name_plural = "Contact Person"


class Director(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(validators=[EmailValidator(message='Enter a valid email address.')])
    address = models.TextField()
    pan_no = models.CharField(max_length=10, unique=True, validators=[RegexValidator(regex=r'^[A-Z]{5}[0-9]{4}[A-Z]{1}$', message='Enter a valid PAN number.')])
    tan_no = models.CharField(max_length=10, validators=[RegexValidator(regex=r'^[A-Z]{4}[0-9]{5}[A-Z]{1}$', message='Enter a valid TAN number.')])
    aadhar_no = models.CharField(max_length=12, validators=[RegexValidator(regex=r'^\d{12}$', message='Enter a valid 12-digit Aadhar number.')])
    din_no = models.CharField(max_length=8, validators=[RegexValidator(regex=r'^\d{8}$', message='Enter a valid 8-digit DIN number.')])
    start_date = models.DateField()
    exit_date = models.DateField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Director"


class DirectorCompanyMapping(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    Director = models.ForeignKey(Director, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.Director.name} ({self.company.company_name}"

    class Meta:
        verbose_name_plural = "Director Company Mapping"


class ARNTracking(models.Model):
    STATUS_CHOICES = [
        ('Rejected', 'Rejected'),
        ('Progressing', 'Progressing'),
        ('Accepted'     , 'Accepted'),
        ('Pending', 'Pending'),
    ]
    sl_no = models.PositiveIntegerField(unique=True)
    trade_name = models.CharField(max_length=255)
    gstn = models.CharField(
        max_length=15,
        validators=[RegexValidator(
            regex=r'^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$',
            message="Invalid GSTN format"
        )]
    )
    purpose = models.TextField()
    arn_number = models.CharField(max_length=50, unique=True)
    dated = models.DateField()
    assigned_to = models.CharField(max_length=255)
    reply_due_date = models.DateField()
    current_status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='Pending')

    class Meta:
        verbose_name_plural = 'ARN Tracking Records'

    def __str__(self):
        return f"ARN Tracking: {self.sl_no}"


class ArnCommand(models.Model):
    arn_record = models.ForeignKey(ARNTracking, on_delete=models.CASCADE, related_name='commands')
    content = models.TextField()
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'ARN Commands'

    def __str__(self):
        return f"Command for {self.arn_record.arn_number} by {self.added_by.username} on {self.timestamp}"


class Task(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('In Progress', 'In Progress'),
        ('Completed', 'Completed'),

    ]

    PRIORITY_CHOICES = [
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High'),

    ]

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES)
    assignees = models.ManyToManyField(User, related_name='tasks', blank=True)
    due_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Tasks"


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Comment by {self.author} on {self.task.title}"

    class Meta:
        verbose_name_plural = "Comments"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>

    <!-- App favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">

    <!-- Plugin css -->
    <link href={% static "assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %} rel="stylesheet"
          type="text/css"/>
    <link href={% static 'assets/vendor/select2/css/select2.min.css' %} rel="stylesheet" type="text/css" />
    <!-- Theme Config Js -->
    <script src={% static "assets/js/hyper-config.js" %}></script>

    <!-- App css -->
    <link href="{% static 'assets/css/app-saas.min.css' %}" rel="stylesheet" type="text/css" id="app-style"/>

    <!-- Icons css -->
    <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css"/>
</head>

<body>
<!-- Begin page -->
<div class="wrapper">
    {% include 'components/topbar.html' %}
    {% include 'components/sidebar.html' %}
    <div class="content-page">
        <div class="content">

            {% block body %}
                
            {% endblock body %}


        </div> <!-- content -->

        <!-- Footer Start -->
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Zapuza - zapuza.com | v-1.0
                    </div>
                    <div class="col-md-6">
                        <div class="text-md-end footer-links d-none d-md-block">
                            <a href="javascript: void(0);">About</a>
                            <a href="javascript: void(0);">Support</a>
                            <a href="javascript: void(0);">Contact Us</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->

    </div>

    <!-- ============================================================== -->
    <!-- End Page content -->
    <!-- ============================================================== -->

</div>
<!-- END wrapper -->

<!-- Vendor js -->
<script src="{% static 'assets/js/vendor.min.js' %}"></script>

<!-- Bootstrap Datepicker js -->
<script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>

<script src="{% static 'assets/vendor/chart.js/chart.min.js' %}"></script>

<script src="{% static 'assets/vendor/chart.js/chart.min.js' %}"></script>
<script src="{% static 'assets/vendor/select2/js/select2.min.js' %}"></script>
<!-- Apex Charts js -->
<script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>

<!-- CRM Project Dashboard Demo js -->
<script src="{% static 'assets/js/pages/demo.crm-project.js' %}"></script>

<!-- App js -->
<script src="{% static 'assets/js/app.min.js' %}"></script>
<script src="{% static 'assets/js/hyper-config.js' %}"></script>


</body>
</html>

templates/director_details.html
{% extends "base.html" %}
{%load static%}


{% block title %}{{ director.name }} Details{% endblock title %}

{% block body %}

                <!-- Start Content-->
                <div class="container-fluid">

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box">
                                <div class="page-title-right">
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">Hyper</a></li>
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                                        <li class="breadcrumb-item active">Profile</li>
                                    </ol>
                                </div>
                                <h4 class="page-title">Profile</h4>
                            </div>
                        </div>
                    </div>
                    <!-- end page title -->


                    <div class="row">
                        <div class="col-sm-12">
                            <!-- Profile -->
                            <div class="card bg-primary">
                                <div class="card-body profile-user-box">
                                    <div class="row">
                                        <div class="col-sm-8">
                                            <div class="row align-items-center">
                                                <div class="col-auto">
                                                    <div class="avatar-lg">
                                                        <img src={% static "assets/images/users/avatar-1.jpg" %} alt="{{ director.name }}" class="rounded-circle img-thumbnail">
                                                    </div>
                                                </div>
                                                <div class="col">
                                                    <div>
                                                        <h4 class="mt-1 mb-1 text-white">{{ director.name }}</h4>
                                                        <p class="font-13 text-white-50"> {{ director.d_id }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div> <!-- end col-->

                                        <div class="col-sm-4">
                                            <div class="text-center mt-sm-0 mt-3 text-sm-end">
                                                <button type="button" class="btn btn-light">
                                                    <i class="mdi mdi-account-edit me-1"></i> Edit Profile
                                                </button>
                                            </div>
                                        </div> <!-- end col-->
                                    </div> <!-- end row -->

                                </div> <!-- end card-body/ profile-user-box-->
                            </div><!--end profile/ card -->
                        </div> <!-- end col-->
                    </div>
                    <!-- end row -->


                    <div class="row">
                        <div class="col-xl-12">
                            <!-- Personal-Information -->
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="header-title mt-0 mb-3">Director Information</h4>
                                    <p class="text-muted font-13">
                                        Hye, I’m {{director.name}},residing in this beautiful world. I create websites and mobile apps with great UX and UI design. I have done work with big companies like Nokia, Google and Yahoo. Meet me or Contact me for any queries. One Extra line for filling space. Fill as many you want.
                                    </p>

                                    <hr/>

                                    <div class="text-start">
                                        <p class="text-muted"><strong>Director ID :</strong> <span class="ms-2">{{ director.d_id }}</span></p>
                                        <p class="text-muted"><strong>Director Name :</strong> <span class="ms-2">{{ director.name }}</span></p>
                                        <p class="text-muted"><strong>Email :</strong> <span class="ms-2">{{ director.email|default:"N/A" }}</span></p>
                                        <p class="text-muted"><strong>Address :</strong> <span class="ms-2">{{ director.address|default:"N/A" }}</span></p>
                                        <p class="text-muted"><strong>PAN Number :</strong> <span class="ms-2">{{ director.pan_no|default:"N/A" }}</span></p>
                                        <p class="text-muted"><strong>TAN Number :</strong> <span class="ms-2">{{ director.tan_no|default:"N/A" }}</span></p>
                                        <p class="text-muted"><strong>Aadhar Number :</strong> <span class="ms-2">{{ director.aadhar_no|default:"N/A" }}</span></p>
                                        <p class="text-muted"><strong>DIN Number :</strong> <span class="ms-2">{{ director.din_no|default:"N/A" }}</span></p>

                                        <p class="text-muted mb-0" id="tooltip-container"><strong>Elsewhere :</strong>
                                            <a class="d-inline-block ms-2 text-muted" data-bs-container="#tooltip-container" data-bs-placement="top" data-bs-toggle="tooltip" href="" title="Facebook"><i class="mdi mdi-facebook"></i></a>
                                            <a class="d-inline-block ms-2 text-muted" data-bs-container="#tooltip-container" data-bs-placement="top" data-bs-toggle="tooltip" href="" title="Twitter"><i class="mdi mdi-twitter"></i></a>
                                            <a class="d-inline-block ms-2 text-muted" data-bs-container="#tooltip-container" data-bs-placement="top" data-bs-toggle="tooltip" href="" title="Skype"><i class="mdi mdi-skype"></i></a>
                                        </p>

                                    </div>
                                </div>
                            </div>
                            <!-- Personal-Information -->
                        </div> <!-- end col-->
                    </div>
                    <!-- end row -->

                    <div class="card">
                                <div class="card-body">
                                    <h4 class="header-title mb-3">My Company</h4>

                                    <div class="table-responsive">
                                        <table class="table table-hover table-centered mb-0">
                                            <thead>
                                                <tr>
                                                    <th>Company Name</th>
                                                    <th>PAN NUMBER</th>
                                                    <th>Website</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                    {% for mapping in director.directorcompanymapping_set.all %}
                                                    <tr>
                                                        <td>
                                                            <a href="{% url 'client_detail' mapping.company.id %}" target="_blank" rel="noopener">{{ mapping.company.company_name }}</a>
                                                        </td>
                                                        <td>
                                                            {{ mapping.company.pan_number }}
                                                        </td>
                                                        <td>
                                                            <a href="{{ mapping.company.website }}" target="_blank" rel="noopener">{{ mapping.company.website }}</a>
                                                        </td>
                                                    </tr>
                                                    {% empty %}
                                                    <tr>
                                                        <td colspan="3">No Company Assigned</td>
                                                    </tr>
                                                    {% endfor %}
                                            </tbody>


                                        </table>
                                    </div> <!-- end table responsive-->
                                </div> <!-- end col-->
                            </div> <!-- end row-->

                </div> <!-- container -->


{% endblock body %}

templates/directors.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Directors | Hyper - Responsive Bootstrap 5 Admin Dashboard
{% endblock title %}

{% block body %}

<div class="container-fluid">

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box">
                                <div class="page-title-right">
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">Hyper</a></li>
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                        <li class="breadcrumb-item active">Directors</li>
                                    </ol>
                                </div>
                                <h4 class="page-title">Directors</h4>
                            </div>
                        </div>
                    </div>
                    <!-- end page title -->

                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="row mb-2">
                                        <div class="col-sm-5">
                                            <a href="javascript:void(0);" class="btn btn-danger mb-2"><i class="mdi mdi-plus-circle me-2"></i> Add Director</a>
                                        </div>
                                        <div class="col-sm-7">
                                            <div class="text-sm-end">
                                                <button type="button" class="btn btn-success mb-2 me-1"><i class="mdi mdi-cog"></i></button>
                                                <button type="button" class="btn btn-light mb-2 me-1">Import</button>
                                                <button type="button" class="btn btn-light mb-2">Export</button>
                                            </div>
                                        </div><!-- end col-->
                                    </div>

                                    <div class="table-responsive">
                                        <table class="table table-centered table-striped dt-responsive nowrap w-100" id="products-datatable">
                                            <thead>
                                                <tr>
                                                    <th style="width: 20px;">
                                                        <div class="form-check">
                                                            <input type="checkbox" class="form-check-input" id="customCheck1">
                                                            <label class="form-check-label" for="customCheck1">&nbsp;</label>
                                                        </div>
                                                    </th>
                                                    <th>Director ID</th>
                                                    <th>Director Name</th>
                                                    <th>Company</th>
                                                    <th>Director Email</th>
                                                    <th>Address</th>
                                                    <th>PAN NO</th>
                                                    <th>TAN NO</th>
                                                    <th>AADHAR NO</th>
                                                    <th>DIN NO</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for director in directors %}
                                                <tr>
                                                    <td>
                                                        <div class="form-check">
                                                            <input type="checkbox" class="form-check-input" id="customCheck2">
                                                            <label class="form-check-label" for="customCheck2">&nbsp;</label>
                                                        </div>
                                                    </td>
                                                    <td class="table-user">
                                                        <a href="{% url 'director_detail' director.d_id %}">{{ director.d_id }}</a>
                                                    </td>
                                                    <td>
                                                        {{ director.name }}
                                                    </td>

                                                    <td>
                                                        {% for mapping in director.directorcompanymapping_set.all %}
                                                            {{ mapping.company.company_name }}{% if not forloop.last %}, {% endif %}
                                                        {% empty %}
                                                            No Company Assigned
                                                        {% endfor %}
                                                    </td>

                                                    <td>
                                                        {{ director.email }}
                                                    </td>
                                                    <td>
                                                        {{ director.address|default:"N/A" }}
                                                    </td>
                                                    <td>
                                                        {{ director.pan_no|default:"N/A" }}
                                                    </td>

                                                    <td>
                                                        {{ director.tan_no|default:"N/A" }}
                                                    </td>

                                                    <td>
                                                        {{ director.aadhar_no|default:"N/A" }}
                                                    </td>
                                                    <td>
                                                        {{ director.din_no|default:"N/A" }}
                                                    </td>

                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div> <!-- end card-body-->
                            </div> <!-- end card-->
                        </div> <!-- end col -->
                    </div>
                    <!-- end row -->

{% endblock body %}